apiVersion: apps/v1
kind: Deployment
metadata:
  name: new
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: tpouche94/webapp-application
        ports:
        - containerPort: 3900
