apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 3900
      targetPort: 3900
