apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: tpouche94/mywebapp
        ports:
        - containerPort: 80
        
        ---
        # service type nodeport
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8085
