apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      volumes:
      - name: cache-volume
        hostPath:
          path: /cache-volume
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: cache-volume
          mountPath: /cache
        ports:
        - containerPort: 80
        
        ---
        # service type nodeport
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
